pubman/urls.py
'''URLconf for pubman

These are:
    /    Index of articles page. Good for a homepage.
    /mediaobject/*
    /article/*
    /story/* 
    /copyright/*
    /feed/rss/
    /feed/atom/
    /i18n/*
    /accounts/*
    /comments/*
    /contact/
    /profiles/*
    /sitemap.xml
'''

from django.conf.urls.defaults import *
from pubman import settings

from django.views.generic import list_detail
from django.views.generic.simple import direct_to_template

from pubman.views import media_object_detail, search
from pubman.models import Story, Copyright
from pubman.feeds import LatestArticlesRSSFeed, LatestArticlesAtomFeed

from django.contrib.sitemaps import FlatPageSitemap
from contact_form.views import contact_form

from pubman.sitemap import ArticleSitemap, StorySitemap, TranslationSitemap 
from pubman.forms import PubmanContactForm

import datetime

story_info = {
    "queryset" : Story.objects.filter(publication_stage='P').\
        filter(date_published__lte = datetime.datetime.now()).\
        order_by('-date_published'),
    "paginate_by" : settings.STORIES_PER_PAGE, 
}

copyright_info = {
    "queryset" : Copyright.objects.all(),
}


sitemaps = {
    'flatpages': FlatPageSitemap,
    'article': ArticleSitemap,
    'story': StorySitemap, 
    'translation': TranslationSitemap,
}


urlpatterns = patterns('pubman.views',
    (r'^$', 'index'),
    url(r'^mediaobject/(?P<slug>[a-zA-Z0-9-\s_]+)/$', 
     media_object_detail,
     name='media_object_detail_view'),
    
    (r'^article/(?P<article_id>\d+)/$', 'article_detail_by_id'),
    url(r'^article/(?P<article_slug>[a-zA-Z0-9-_]+)/$', 
        'article_detail', name='article_detail_view'),    
    
    url(r'^article/translation/(?P<article_slug>[a-zA-Z0-9-_]+)/(?P<article_lang>[a-zA-Z0-9-_]+)/$', 
        'article_detail', name='translated_article'),    

    (r'^article/tag/(?P<tag_expression>[\"\^\'\~\&\|\(\)a-zA-Z0-9-\s_]+)/$', 'tag_view', 
     {'model_name': 'article', }, 
    'article_tag'),

    (r'^story/$', list_detail.object_list, story_info),
    (r'^story/(?P<story_id>\d+)/$', 'story_detail_by_id'),
    (r'^story/(?P<story_slug>[a-zA-Z0-9-_]+)/$', 'story_detail'),
    url(r'^copyright/(?P<object_id>\d+)/$', 
        list_detail.object_detail, 
        copyright_info,
        name='copyright_view'),
    
    (r'^markdownpreview/$', 'markdownpreview'),
    (r'^clearcache/$', 'clear_cache')
)

if 'search' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,
                        (r'^search/$', search),)

if 'rss' in settings.URLCONF_VIEWS: 
    urlpatterns += patterns(settings.URLCONF_ROOT,
            url(r'^feed/rss/articles/$', LatestArticlesRSSFeed(), name='rss-feed-articles'),)
    
if 'atom' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,                
            url(r'^feed/atom/articles/$', LatestArticlesAtomFeed(), name='atom-feed-articles'),)

if 'i18n' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,         
            url(r'^i18n/setlangform/', direct_to_template,
            {'template': 'pubman/set_language.html'}, name='setlangform' ),  
            (r'^i18n/', include('django.conf.urls.i18n')),)

if 'accounts' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,    
            (r'^accounts/', include('registration.urls')),)

if 'comments' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,    
            (r'^comments/', include('django.contrib.comments.urls')),)

if 'contact' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,
            
    (r'^contact/$', contact_form, {'form_class': PubmanContactForm}),                            
    (r'^contact/', include('contact_form.urls')),)
    
if 'profiles' in  settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,
            (r'^profiles/create/$', 'pubman.views.edit_profile'),
            (r'^profiles/edit/$', 'pubman.views.edit_profile'),
            (r'^profiles/', include('profiles.urls')),)
    
if 'sitemap' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,
    (r'^sitemap\.xml', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),)        

if 'filebrowser' in settings.URLCONF_VIEWS:
    urlpatterns += patterns(settings.URLCONF_ROOT,
    (r'^admin/filebrowser/', include('filebrowser.urls')),)

pubman/models.py
"""Models for handling publication content in Publication Manager.

Models:

    UserProfile: Extension to django's User model.

    Subscription: Tracks subscriptions to this publication's articles.
        Not fully implemented yet. Low priority given that I'm not much
        interested in this feature.

    Copyright: These are foreign keys in all models inheriting from ContentObject
    and represent the different types of copyrights that this publication's
    materials can be published under.

    Credit: Model representing people or institutions who are photographers,
    writers editors etc.

    OrderedCredit: Used to order authors/credits for content models
        (articles, media objects, stories and translations).

    ContentObject: Abstract base class that Article, Story, MediaObject and
        Translation inherit from.

    MediaObject: Represents images, video etc. Needs a lot more work.

    Article: Stores article items. This is the central model in pubman around
        which most of the other models work.

    OutOfDate: Reserved for future use to represent articles that are out of
        date and have been superceded.

    HistoricalEdit: Reserved for future use to represent modifications to
        articles, a bit like a Wiki.

    Translation: Model whose instances are a translation of an article.

    FurtherReading: Each instance is a link to a recommended further reading
        for an article. These recommended readings can be other articles,
        stories or external URLs.

    Story: Each instance contains a collection of articles. Nice for featuring
        a set of related articles or creating tutorials.

    OrderedArticle: Model used to order an article within a story.

    FeaturedStory: OneToOne with Story that is used to indicate what stories
        should be featured, e.g. on the front page of the website.

    FeaturedWebpageGroup: Model for representing a collection of links to
        external sites. E.g. for representing links, perhaps blogrolls etc.

    WebpageLink: Each instance represents link to external URL. There are many
        of these in each FeaturedWebPageGroup via WebPageOrder.

    OrderedWebpage: Used to order the WebPageLinks within a FeaturedWebPageGroup.

    FeaturedRSSFeed: Extremely simple model for keeping external feeds that the
        website must get.

"""

from django.db import models
from django.db.models import Q
from datetime import datetime, timedelta

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.utils.safestring import mark_safe
from django.template.defaultfilters import slugify
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User
from django.contrib.comments.moderation import CommentModerator, moderator

from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings as django_settings

import feedparser

from django_countries import CountryField
from sorl.thumbnail import ImageField, get_thumbnail
from tagging.fields import TagField

from pubman.settings import MAX_CHAR_FIELD_LENGTH as MAX_LENGTH
from pubman.settings import ALL_LANGUAGES, DEFAULT_LANGUAGE_INDEX
from pubman import settings
from pubman.utils import set_extra_permissions, is_published, make_slug_unique,\
    permission_to_view_Q, permission_to_view_item, credit_list, validate_link,\
    get_link, get_caption


# "Monkey patch" the username field to be 75 chars long so that
# emails can be entered in authentication username field.
AuthenticationForm.base_fields['username'].max_length = 75

users_who_can_edit_this_help_text = _("Indicate which users can edit or delete " +\
                    "this content. ")

slug_field_help_text = _('This is the name of the item in its URL. ' +\
                       'It is automatically created from the title. ' +\
                       'If you do edit it, it may only contain letters, ' +\
                       'digits, hyphens and underscores. ' +\
                       'The slug must be unique. ')

publication_stage_help_text = _('This item only becomes available to site users '
        'when you change this to published and the publication date has been reached. ')

COMPLEXITY_CHOICES = (
    ('S', _('simple')),
    ('D', _('difficult'))
)

PUBLICATION_STAGES = (
    # ('W', _('withdrawn')),
    ('D', _('draft')),
    # ('S', _('submitted')),
    ('P', _('published')),
)

MEDIA_TYPES = (
    ('I', _('Photos or Images on this site')),
    ('V',_('Video on this site')),
    ('E', _('Embedded image, map or video from another site')),
)

TYPES_OF_FURTHER_READING = (
    ('00', _('Related articles')),
    ('05', _('Further Reading')),
    ('10', _('See also')),
    ('15', _('Source')),
    ('20', _('Reference'))
)

TEXT_FORMATS = (
    ('T', _('Plain text')),
    ('R', _('reStructuredText')),
    ('M', _('Markdown')),
    ('H', _('HTML')),
)

PAGE_BREAK_STRATEGIES = (
    ('N', _('No breaks')),
    ('C', _('Break when encountering this: ' +\
             settings.PAGE_BREAK_CODE)),
    )

EDITOR_DISPLAY_STYLES = (
    ('N', _('Do not display editors')),
    ('E', _('Display as editors')),
    ('A', _('Display as authors')),
    )

SEXES= (('F',_('Female')),
        ('M', _('Male'),))

VIDEO_LOAD_CHOICES = (
        ('A', _('Autoplay')),
        ('D', _('Default')),
        ('N', _('Do not preload')),
        ('P', _('Do preload')),
    )

# Constants used by MediaObject class to determine if HTML for a slideshow
# must be generated.
SLIDESHOW = -1
ALL_IMAGES = -2


class UserProfile(models.Model):
    '''Extension to Django's User model
    '''
    user = models.OneToOneField(User)
    avatar = ImageField(upload_to=settings.UPLOAD_AVATAR_FOLDER_MASK,
                        blank=True,
                        verbose_name='Photo or avatar')
    date_of_birth = models.DateField(blank=True, null=True)
    url = models.URLField(blank=True, verify_exists=False,
                          verbose_name='Your website')
    sex = models.CharField(max_length=1,
                           choices=SEXES, blank=True, null=True)
    physical_address = models.CharField(max_length=MAX_LENGTH,
                            blank=True)
    physical_address_code = models.CharField(max_length=12,
                            blank=True)
    physical_address_city = models.CharField(max_length=MAX_LENGTH,
                            blank=True)
    physical_address_country = CountryField(blank=True)
    postal_address = models.CharField(max_length=MAX_LENGTH,
                            blank=True)
    postal_address_code = models.CharField(max_length=12,
                            blank=True)
    postal_address_city = models.CharField(max_length=MAX_LENGTH,
                            blank=True)
    postal_address_country = CountryField(blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = _('user profile')
        verbose_name_plural = _('user profiles')

class Subscription(models.Model):
    '''Tracks subscriptions to the publication's articles. Not fully implemented
    yet.
    '''
    subscriber = models.ForeignKey(UserProfile)
    date_from = models.DateField()
    date_to = models.DateField()

    @staticmethod
    def is_subscriber(user):
        if Subscription.objects.filter(user__id=user.id,
                                date_from__lt=datetime.today(),
                                date_to__gt=datetime.today()).count()>0:
            return True
        else:
            return False

    class Meta:
        verbose_name = _('subscriber')
        verbose_name_plural = _('subscribers')


class Copyright(models.Model):
    """This class represents the different types of copyrights that
    can be applied to an image or article.
    """
    title = models.CharField(max_length=MAX_LENGTH)
    easy_text = models.TextField(blank=True,
        help_text=_('Explanation of copyright for non-experts.'))
    legal_text = models.TextField(blank=True,
        help_text = _('Actual legal text of the copyright.'))
    html_text = models.TextField(blank=True,
        help_text = _('HTML that can be placed on web pages '
                      'of objects under this copyright. '))
    url = models.URLField(blank=True,
        verify_exists=False,
        help_text=_('Web address for this copyright.'))

    def describe(self):
        return self.easy_text

    @models.permalink
    def get_absolute_url(self):
        return ('copyright_view', [str(self.id)])

    def get_name(self):
        return self._meta.verbose_name

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = _('copyright')
        verbose_name_plural = _('copyrights')

class Credit(models.Model):
    """Model representing people or institutions who are photographers,
    writers editors etc.
    """
    is_person = models.BooleanField(default=True,
                                 verbose_name='Is this a person?',
                                 help_text=_('Check this field if this is a '
                                 'person (e.g. Thomas Hardy) as opposed to '
                                 'an institution (e.g. Reuters).'))
    first_names = models.CharField(blank=True, max_length=MAX_LENGTH,
                                  verbose_name=_("Person's first names"),
                                  help_text=_('Leave blank for institutions'))
    last_name = models.CharField(max_length=MAX_LENGTH,
                                 verbose_name=_('Name of institution or '
                                 'last name of person'))

pubman/templates/profiles/create_profile.html
{% comment %}
Template adapted from: http://svn.chrisgilmer.net/viewvc.cgi/project/python/django/templates/profiles/edit_profile.html?view=log
For now this template is obsolete. It's functions are handled by edit_profile.html
Leaving it in repository for a bit longer. 
{% endcomment %}

{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ block.super }} - {% trans "Create Profile" %} {% endblock %}
   
{% block content %}
   
<h1>{% trans "Create profile for" %} {{ user }} </h1>
   
<div id="create_profile">
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    
    {% include "form_as_table_snippet.html" %}

    </form>
</div>
  
{% endblock content %} 

pubman/templates/profiles/edit_profile.html
{# template adapted from: http://svn.chrisgilmer.net/viewvc.cgi/project/python/django/templates/profiles/edit_profile.html?view=log#}

{% extends "base.html" %}
{% load i18n %}

{% block scripts %}
    {{block.super}}
    <link type="text/css" href="{{MEDIA_URL}}pubman/css/smoothness/jquery-ui-1.8.6.custom.css" rel="stylesheet" />  
    <script type="text/javascript" src="{{MEDIA_URL}}pubman/js/jquery-1.4.3.min.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}pubman/js/jquery-ui-1.8.6.custom.min.js"></script>
    
    <script>
    $(function() {
        $('.datepicker').datepicker({
            dateFormat: 'yy-mm-dd', 
            changeYear: true ,
            yearRange: '1910:2020'});                
    });
    </script>
    
{% endblock %}


{% block title %}{{ block.super }} - {% trans "Edit Profile" %} {% endblock %}
   
{% block content %}
   
<h1>Edit profile for {{ user }} </h1>
<p>
{% blocktrans %} 
All data except your username, photo and website are kept private  
and can only be seen by you and the system administrators.
{% endblocktrans %}
</p>
<a href="{% url django.contrib.auth.views.password_change %}" target="_blank">
<p>{% trans "Change your password" %}.</p>
</a>

<div id="user_profile_form">   
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    <ul>
    {{user_form.as_ul}}
    {{profile_form.as_ul}}
    <li>
    <input type="submit" name="submit" class="btn" value="{% trans 'Update' %}" id="submit">
    </li>
    </ul>            
</form>
</div>
  
{% endblock content %} 

pubman/templates/profiles/profile_detail.html
{# template adapted from: http://svn.chrisgilmer.net/viewvc.cgi/project/python/django/templates/profiles/edit_profile.html?view=log#}
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{{ block.super }} - {{ profile.user.username }}{% endblock %}

{% block content %}

{% if profile %}

    {% if not user.is_authenticated  %}
        <p class="messages">{% trans "Sorry, but you may not view this profile" %}.</p>
    {% else %}    
        {% if user == profile.user or user.is_superuser %}
            <div id="profile_info">
            <h1>{% trans "Profile for user" %}: {{ profile.user.username }}</h1>            
            
            <div id="profile_image">

                {% thumbnail profile.avatar settings.DEFAULT_PASSPORT_DIM as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                title="{{profile.user.username}}" />
                {% endthumbnail %}            
            
            </div>
            
            <p><a href="{% url profiles_edit_profile %}">Edit your profile</a></p>            
            <div id="profile_table">
            <table>
                <tr>
                <td>Name:</td>
                <td>{{ profile.user.get_full_name }}</td> 
                </tr>           

                <tr>
                <td>{% trans "Email" %}:</td>
                <td>{{ profile.user.email }}</td>
                </tr>
                                
                <tr>
                <td>{% trans "Sex" %}:</td>
                <td>{{ profile.get_sex_display }}</td>
                </tr>

                <tr>
                <td>{% trans "Date of birth" %}:</td>
                <td>{{ profile.date_of_birth }}</td>
                </tr>

                <tr>
                <td>{% trans "URL" %}:</td>
                <td>{{ profile.url }}</td>
                </tr>

                <tr>
                <td>{% trans "Physical address" %}:</td>
                <td>{{ profile.physical_address }}</td>
                </tr>

                <tr>
                <td>{% trans "Physical address code" %}:</td>
                <td>{{ profile.physical_address_code }}</td>
                </tr>

                <tr>
                <td>{% trans "Physical address city" %}:</td>
                <td>{{ profile.physical_address_city }}</td>
                </tr>

                <tr>
                <td>{% trans "Physical address country" %}:</td>
                <td>{{ profile.get_physical_address_country_display }}</td>
                </tr>

                <tr>
                <td>{% trans "Postal address" %}:</td>
                <td>{{ profile.postal_address }}</td>
                </tr>

                <tr>
                <td>{% trans "Postal address code" %}:</td>
                <td>{{ profile.postal_address_code }}</td>
                </tr>

                <tr>
                <td>{% trans "Postal address city" %}:</td>
                <td>{{ profile.postal_address_city }}</td>
                </tr>

                <tr>
                <td>{% trans "Postal address country" %}:</td>
                <td>{{ profile.get_postal_address_country_display }}</td>
                </tr>

                <tr>
                <td>{% trans "Last login" %}:</td>
                <td>{{ profile.user.last_login }}</td>
                </tr>
                <tr>
                <td>{% trans "Member since" %}:</td>
                <td>{{ profile.user.date_joined }}</td>
                </tr>
            </table>
            </div>

            </div>
        {% else %}
            <p class="messages">{% trans "Sorry, but you may not view this profile" %}.</p>            
        {% endif %}
    
    {% endif %}        

{% endif %}

{% endblock %}
 

pubman/templates/profiles/profile_list.html
{# template adapted from: http://svn.chrisgilmer.net/viewvc.cgi/project/python/django/templates/profiles/edit_profile.html?view=log#}
{% extends "base.html" %}
   
{% block title %}Profile List - {{ block.super }}{% endblock %}
   
{% block content %}
   
<h1>Profile List</h1>
   
<div id="profile_list">
<ul>
{% for object in object_list|dictsort:"user.username" %}
<li><a href="{% url profiles_profile_detail object.user.username %}">{{ object.user.username }}</a></li>
{% endfor %}
</ul>
</div>
  
{% endblock %} 